apiVersion: networking.istio.io/v1alpha3  
kind: DestinationRule  
metadata:  
  name: yorkie
  namespace: yorkie
spec:  
  host: yorkie
  trafficPolicy:  
    portLevelSettings:  
      - port:  
          number: 11101
        loadBalancer:  
          consistentHash:  
            maglev:  
              tableSize: 65537
            httpHeaderName: x-shard-key
      - port:  
          number: 11103
        loadBalancer:  
          consistentHash:  
            maglev:  
              tableSize: 65537
            httpHeaderName: x-shard-key